export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"

export const REQUESTING_ROBOTS = "REQUESTING_ROBOTS"
export const RECEIVED_ROBOTS = "RECEIVED_ROBOT"
export const ERROR_RECEIVING_ROBOTS = "ERROR_RECEIVING_ROBOTS"