export const SEARCH_FIELD = "SEARCH FIELD";
export const REQUESTING_POKEDEX = "REQUESTING_POKEDEX";
export const RECIEVED_POKEDEX = "RECIEVED_POKEDEX";
export const COMPLETING_POKEDEX = "POKDEX_COMPLETED";